version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:v0.9.13
    stdin_open: true
    tty: true
    expose:
      - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=${RANCHER_STACK_NAME}/lb
  funcao-api:
    mem_limit: 536870912 #512M
    mem_reservation: 402653184 #384M
    image: 887865187465.dkr.ecr.sa-east-1.amazonaws.com/funcao-api:${TAG_VERSION}
    environment:
      SPRING_PROFILES_ACTIVE: ${DEPLOYENV}
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      SPRING_CLOUD_CONFIG_LABEL: unificacao-pch
      SPRING_CLOUD_CONFIG_USERNAME: ${CONFIG_SERVER_USERNAME}
      SPRING_CLOUD_CONFIG_PASSWORD: ${CONFIG_SERVER_PASSWORD}
      JAVA_OPTS: -Xmx384m
      TZ: America/Sao_Paulo
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=${RANCHER_STACK_NAME}/funcao-api
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always