version: '2'
services:
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
        - priority: 1
          path:  /api/funcao
          protocol: http
          service: funcao-api
          source_port: 80
          target_port: 8080
    health_check:
      healthy_threshold: 1
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 2
      initializing_timeout: 60000
      interval: 3000
      strategy: recreate
      reinitializing_timeout: 60000
  funcao-api:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 3
      response_timeout: 5000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 10000
      strategy: recreate
      request_line: GET /api/funcao/actuator/health HTTP/1.0
      reinitializing_timeout: 60000

